// <auto-generated />
namespace MovieFu.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Movies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Movies));
        
        string IMigrationMetadata.Id
        {
            get { return "201305080430325_Movies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
